#!/bin/bash

pushd ~/emsdk
source ./emsdk_env.sh
popd

emcc -Iinclude src/main.cpp -O0 -std=c++14 -s TOTAL_MEMORY=33554432 -s USE_WEBGL2=1 -s FULL_ES3=1 -s USE_SDL=2 -o index.html \
  -I"/usr/local/Cellar/glm/0.9.9.0/include" \
  -I"/Users/jharding/rapidjson/include" \
  --preload-file models/cube_m.json \
  --preload-file assets/multi.bmp \
  --preload-file shaders/simple.es300.vert \
  --preload-file shaders/simple.es300.frag
